### ISSUE TITLE
Can access to send share url only as user, not visitor

### ISSUE THREAD

**Issue by prog-amateur2** [YunoHost-Apps/send_ynh#14]
### Describe the bug

Hello, when I share a link to a visitor, (s)he does not visit the send page but the Yunohost connection portal. 
On my (user) side, I can access to the send share webpage.

When I check in the admin panel, I can see that : 
- all users have access to Send
- and that Visitors are allowed to use send api only 

How to solve this issue ? I think it is a setup issue but the documentation give 404 error. 

Thank you for your kind help. 

### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 4.3.6.2 
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: stable branch
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

*1. share a link from user panel
2. take another computer / phone and go to the link
3. see the Yunohost portal instead of send link*

### Expected behavior

*The visitor should access to the send share webpage.*

**Comment by tituspijean** [comment]
> and that Visitors are allowed to use send api only

Try giving the `Send` permission to visitors too.

---

Am I right to guess that you want to restrict who can create new uploads but allow anyone to download?

**Comment by prog-amateur2** [comment]
> Am I right to guess that you want to restrict who can create new uploads but allow anyone to download?

Yes this is it, exactly. I don't want people to make link, just to download them.

**Comment by tituspijean** [comment]
Unfortunately that is something that needs to be coded upstream. Here is a ticket talking about a similar feature: https://github.com/timvisee/send/issues/32

For reference, I have tried adding a permission on the `/download` path so that visitors have access there but not to `/`. However most of the app's code is served under `/` so that permission pretty much breaks it.

**Comment by prog-amateur2** [comment]
> I have tried adding a permission on the `/download` path so that visitors have access there but not to `/`

Thank you. About permissions, what do you think if I could `chmod` the directory with `764` (`user = rwx, group = rw, others = read only`) ? In that case, what is the complete directory path so I don't mistake please ?

By the way, Jirafeau was my first share service, I don't know why I have stopped to use it. 

Thank you very much !

**Comment by tituspijean** [comment]
> About permissions, what do you think if I could chmod the directory with 764 (user = rwx, group = rw, others = read only) ? In that case, what is the complete directory path so I don't mistake please ?

I was talking about a SSO permission and URL paths.
