### ISSUE TITLE
impossible to install send on yunohost 11.0.10.2

### ISSUE THREAD

**Issue by jbastruz** [YunoHost-Apps/send_ynh#18]
Hi everyone,

I tried to install the send app on my server, but i received some errors, i don't understand the issue, someone could help me ?

I uninstall a previous version of send du to an issue on my server, and i tried to install it again, i didn't forget to remove the `/var/www/send/` folder before, but it seems to have an error in the "app installation script"

https://paste.yunohost.org/raw/cucoyataro

I'm on yunohost 11.0.10.2, and I try to install the send version 3.4.21~ynh1

**Comment by tituspijean** [comment]
> 2022-11-04 10:06:03,702: DEBUG - + sudo -u send env PATH=/opt/node_n/n/versions/node/16.13/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /opt/node_n/n/versions/node/16.13/bin/npm install
2022-11-04 10:08:47,814: DEBUG - /usr/share/yunohost/helpers.d/user: line 179: 29029 Killed                  sudo -u "$user" "$@"

`Killed` means your server ran out of memory during the building of the app. Consider adding a swap file to extend its available memory. :)
