### ISSUE TITLE
Send fails to open a WS connection

### ISSUE THREAD

**Issue by hexandcube** [YunoHost-Apps/send_ynh#9]
Send fails to open a WebSocket connection to yunohost.server/api/ws (the server returns HTTP 404).

![image](https://user-images.githubusercontent.com/41151156/143770470-ed3bfde6-b104-4473-b083-58de9aead193.png)
![image](https://user-images.githubusercontent.com/41151156/143770483-f003e90b-787b-41b0-a7c1-6294cdbbde4a.png)
![image](https://user-images.githubusercontent.com/41151156/143770552-9eebe149-0480-4749-8797-284d0d04e453.png)

Because of that, uploading files is not possible (uploading is stuck at 0%).

![image](https://user-images.githubusercontent.com/41151156/143770245-0bcb79cb-8791-4079-86cb-6ddd20f7b6fe.png)

I believe this is a problem with the Yunohost server configuration and not the Send project itself, but I'm not 100% sure.

## Steps to reproduce

1. Install Send on a fresh YunoHost instance
2. Open the send app
3. Try to upload a file

## Configuration
**YunoHost version:** 4.3.4.1 (stable)
**Send version:** 3.4.14~ynh1

Tested on the latest versions of Firefox and Chrome

**Comment by ericgaspar** [comment]
is it a public or private install?

**Comment by hexandcube** [comment]
Public

**Comment by ericgaspar** [comment]
I have created two branch with possible fixes. As I cannot reproduce your issue to validat what works, can you test them?
`https://github.com/YunoHost-Apps/send_ynh/tree/api/ws`
`https://github.com/YunoHost-Apps/send_ynh/tree/NGINX-ws`

**Comment by hexandcube** [comment]
I've tried both, but unfortunately they don't fix the issue

**Comment by isAAAc** [comment]
@hexandcube : do you still have this issue since 2021 ?

**Comment by hexandcube** [comment]
Yes, unfortunately I never got it to work

**Comment by hexandcube** [comment]
@isAAAc Are you using a reverse proxy by any chance?

I was able to get it working by adding WS headers in the reverse proxy config to support Websocket connections.

I'm using a Synology NAS as a reverse proxy, so I just went to Reverse Proxy settings, selected the config for Send,
then in the Custom Header tab I've added the Upgrade and Connection headers. On DSM 7 you can just click Create>Websocket.

![image](https://user-images.githubusercontent.com/41151156/221378050-c78027a6-c7e1-4e14-b3be-da4be1f9c3e9.png)

If you're using something else like NGINX as a reverse proxy, make sure to configure it to support Web socket connections
https://www.nginx.com/blog/websocket-nginx/

I'm closing this since it's not an issue with Send, but with my network setup.
